'use client';

import { motion } from 'framer-motion';
import { Target, Server, Leaf, Database, Cpu, Layout, Code2, Globe, TrendingUp, ShieldCheck, Award } from 'lucide-react';

export default function AboutPage() {
  const teamMembers = [
    { name: "Iqra Nazim", role: "Project Lead Frontend Developer", email: "", avatar: "IN" },
    { name: "Ezzah Khan", role: "Backend Developer", email: "", avatar: "EK" },
    { name: "Amina Hassan", role: "Frontend, Designs and Documentation", email: "", avatar: "AH" }
  ];

  return (
    <div className="min-h-screen py-16 px-4 md:px-8 max-w-5xl mx-auto">
      <div className="absolute top-1/4 right-1/4 w-[400px] h-[400px] bg-cyan-400/5 rounded-full blur-[100px] pointer-events-none" />
      <div className="absolute bottom-1/4 left-1/4 w-[300px] h-[300px] bg-green-400/5 rounded-full blur-[100px] pointer-events-none" />

      {/* Hero Section */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-20"
      >
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-400/10 text-cyan-400 mb-6">
          <Leaf className="w-4 h-4" />
          <span className="text-sm font-medium">Platform Knowledge Base</span>
        </div>
        <h1 className="text-4xl md:text-6xl font-bold mb-6">
          Understanding <span className="text-gradient">Environmental</span> Impact
        </h1>
        <p className="text-gray-400 text-lg md:text-xl max-w-3xl mx-auto leading-relaxed">
          EcoAnalyzer utilizes an advanced Multi-Factor Environmental Model powered by Google Gemini AI. Discover how we calculate your footprint, what it means, and how you can gamify your journey to sustainability.
        </p>
      </motion.div>

      {/* Core Educational Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-20">
        
        {/* What are Carbon Footprints? */}
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.1 }}
          className="glass-card p-8 border-l-4 border-l-green-400 hover:shadow-[0_0_30px_rgba(74,222,128,0.1)] transition-all"
        >
          <div className="flex items-center gap-3 mb-4">
            <Globe className="w-6 h-6 text-green-400" />
            <h2 className="text-2xl font-bold">What is a Carbon Footprint?</h2>
          </div>
          <p className="text-gray-400 leading-relaxed">
            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. Everything from the electricity that powers your home, to the fuel used to transport your food, contributes to this invisible metric. Our goal is to make this invisible impact visible.
          </p>
        </motion.div>

        {/* How Impact is Calculated */}
        <motion.div 
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="glass-card p-8 border-l-4 border-l-cyan-400 hover:shadow-[0_0_30px_rgba(34,211,238,0.1)] transition-all"
        >
          <div className="flex items-center gap-3 mb-4">
            <Cpu className="w-6 h-6 text-cyan-400" />
            <h2 className="text-2xl font-bold">How We Calculate Impact</h2>
          </div>
          <p className="text-gray-400 leading-relaxed mb-4">
            We use a <strong>Multi-Factor Environmental Model</strong>. You provide core metrics (like electricity and travel) and advanced optional metrics (like specific liquid consumption or vehicle type). 
          </p>
          <p className="text-gray-400 leading-relaxed">
            This data is sent to our AI (Google Gemini Pro), which cross-references it against vast environmental datasets to generate a personalized <strong>Eco-Score from 0 to 100</strong>.
          </p>
        </motion.div>

        {/* Best Case vs Worst Case */}
        <motion.div 
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.3 }}
          className="glass-card p-8 border-l-4 border-l-purple-400 hover:shadow-[0_0_30px_rgba(168,85,247,0.1)] transition-all"
        >
          <div className="flex items-center gap-3 mb-4">
            <ShieldCheck className="w-6 h-6 text-purple-400" />
            <h2 className="text-2xl font-bold">The Scoring Spectrum</h2>
          </div>
          <div className="space-y-4 text-sm">
            <div className="p-4 bg-green-400/5 rounded-xl border border-green-400/20">
              <strong className="text-green-400 block mb-1">Best Case Scenario (Score: 1 - 30)</strong>
              <span className="text-gray-400">Minimal electricity, plant-based diet, electric vehicles or public transit, and consumption of tap water rather than bottled plastics. Highly sustainable.</span>
            </div>
            <div className="p-4 bg-red-400/5 rounded-xl border border-red-400/20">
              <strong className="text-red-400 block mb-1">Worst Case Scenario (Score: 71 - 100)</strong>
              <span className="text-gray-400">High fossil fuel usage, heavy meat diet, reliance on gas-guzzling vehicles, and high consumption of plastic bottled water. Severely unsustainable.</span>
            </div>
          </div>
        </motion.div>

        {/* Gamification Engine */}
        <motion.div 
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.4 }}
          className="glass-card p-8 border-l-4 border-l-yellow-400 hover:shadow-[0_0_30px_rgba(250,204,21,0.1)] transition-all"
        >
          <div className="flex items-center gap-3 mb-4">
            <Award className="w-6 h-6 text-yellow-400" />
            <h2 className="text-2xl font-bold">Points, Levels & Leaderboard</h2>
          </div>
          <p className="text-gray-400 leading-relaxed mb-4">
            We believe saving the planet should be rewarding. Our Gamification Engine actively tracks your engagement:
          </p>
          <ul className="space-y-2 text-gray-400 list-disc list-inside mb-4">
            <li><strong>Earning Points:</strong> You earn points by analyzing your behavior (+10pts), completing Eco-Quizzes (up to +1000pts), and having community articles approved (+500pts).</li>
            <li><strong>Leveling Up:</strong> For every 50 points you accumulate, your Eco-Level automatically increases.</li>
          </ul>
          <p className="text-gray-400 leading-relaxed">
            Your total score dictates your rank on the <strong>Global Leaderboard</strong>, allowing you to compete with others worldwide in the fight against climate change.
          </p>
        </motion.div>

      </div>

      {/* Team Section */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
        className="flex flex-col gap-8 items-center justify-center max-w-3xl mx-auto"
      >
        <div className="w-full glass-card p-8 md:p-12 border-l-4 border-l-cyan-400">
          <h2 className="text-2xl font-bold mb-8 flex items-center justify-center gap-2 border-b border-white/10 pb-4">
            <svg className="w-6 h-6 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            Project Team
          </h2>
          <div className="space-y-4">
            {teamMembers.map((member, idx) => (
              <div key={idx} className="group flex items-center gap-4 p-4 rounded-xl bg-white/[0.02] border border-white/5 transition-all duration-300 hover:scale-105 hover:bg-white/[0.05] hover:border-cyan-400/30 hover:shadow-[0_0_30px_rgba(34,211,238,0.1)]">
                <div className="w-16 h-16 rounded-full overflow-hidden bg-gradient-to-tr from-green-400 to-cyan-400 flex items-center justify-center text-black font-bold text-xl shrink-0 border-2 border-white/10 relative transition-transform duration-300 group-hover:scale-110 group-hover:border-cyan-400/50">
                  {member.avatar}
                </div>
                <div>
                  <h4 className="font-bold text-gray-200">{member.name}</h4>
                  <p className="text-sm text-gray-500">
                    {member.role}{member.email ? ` • ${member.email}` : ''}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </motion.div>
    </div>
  );
}
