const mongoose = require('mongoose');

const BehaviorLogSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  electricityUsage: {
    type: Number, // kWh per week/month
    required: true,
  },
  waterUsage: {
    type: Number, // Liters per week/month
    required: true,
  },
  wasteGeneration: {
    type: Number, // kg per week/month
    required: true,
  },
  travelDistance: {
    type: Number, // km per week/month
    required: true,
  },
  travelMode: {
    type: String, // Car, Bus, Train, Bike, Walk
    required: true,
  },
  dietType: {
    type: String, // Vegan, Vegetarian, High Meat, Low Meat
    required: true,
  },
  fuelUsage: {
    type: Number, // Optional: Liters/Gallons of fuel used
    required: false,
  },
  liquidConsumption: {
    type: String, // Optional: Tap Water, Bottled Water, Sugary Drinks, Alcohol
    required: false,
  },
  vehicleType: {
    type: String, // Optional: Electric, Fuel, Hybrid, None
    required: false,
  },
  footprintScore: {
    type: Number, // Eco-Score generated by AI
    required: true,
  },
  analysisDetails: {
    type: mongoose.Schema.Types.Mixed, // flexible object for AI generated findings/recommendations
    default: {},
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  isHiddenForUser: {
    type: Boolean,
    default: false,
  },
});

module.exports = mongoose.model('BehaviorLog', BehaviorLogSchema);
